---
- name: Check if already installed
  stat:
    path: ~/.local/share/JetBrains/Toolbox/bin/jetbrains-toolbox
  register: jetbrains_toolbox_bin
  become: no
- name: Download JetBrains Toolbox
  get_url:
    url: https://download-cdn.jetbrains.com/toolbox/jetbrains-toolbox-{{ jetbrains_toolbox_version }}.tar.gz
    checksum: "sha256:{{ jetbrains_toolbox_sha256 }}"
    dest: /tmp/
    mode: 0644
  when: not jetbrains_toolbox_bin.stat.exists
- name: Unarchive JetBrains Toolbox
  unarchive:
    src: /tmp/jetbrains-toolbox-{{ jetbrains_toolbox_version }}.tar.gz
    dest: /tmp
    remote_src: yes
  become: no
  when: not jetbrains_toolbox_bin.stat.exists
- name: Create Toolbox bin directory
  file:
    path: ~/.local/share/JetBrains/Toolbox/bin
    state: directory
    mode: 0755
  become: no
- name: Move JetBrains Toolbox binary
  command: mv /tmp/jetbrains-toolbox-{{ jetbrains_toolbox_version }}/jetbrains-toolbox ~/.local/share/JetBrains/Toolbox/bin/jetbrains-toolbox
  become: no
  changed_when: False
  when: not jetbrains_toolbox_bin.stat.exists
- name: Create launcher directory
  file:
    path: ~/.local/share/applications
    state: directory
    mode: 0755
  become: no
- name: Copy JetBrains Toolbox desktop launcher
  template:
    src: templates/jetbrains-toolbox.desktop.j2
    dest: ~/.local/share/applications/jetbrains-toolbox.desktop
    mode: 0644
  become: no
